---
name: "Nix build (darwin)"
on:
  pull_request:
  push:
  workflow_call:
jobs:
  nix-build-fixture:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@v9
    - uses: cachix/cachix-action@v12
      with:
        name: neorocks
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#fixtures.tree-sitter-norg
