name: Test install fixture on windows

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      # - name: Install C/C++ Compiler
      #   uses: rlalik/setup-cpp-compiler@master
      #   with:
      #     compiler: clang-latest

      - name: Install MSVC Compiler Toolchain
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install Scoop
        uses: MinoruSekine/setup-scoop@v4

      - name: Add rocks-scoop bucket
        run: |
          scoop bucket add neorocks-scoop https://github.com/nvim-neorocks/rocks-scoop.git

      - name: Install luarocks
        run: |
          scoop install neorocks-scoop/luarocks

      - name: Install tree-sitter CLI
        uses: baptiste0928/cargo-install@v3
        with:
          crate: tree-sitter-cli

      - name: Install build dependencies
        run: |
          luarocks --local --lua-version=5.1 make ./luarocks-build-treesitter-parser-scm-1.rockspec

      - name: Install tree-sitter parser
        run: |
          luarocks --local --lua-version=5.1 install tree-sitter-haskell --dev

      - name: Pack and create manifest
        run: |
          luarocks pack tree-sitter-haskell
          luarocks-admin make-manifest --lua-version=5.1 .
          dir
          type manifest-5.1
